### ISSUE TITLE
[Feature] Add world timestamp to `.log` output

### ISSUE THREAD

**Issue by a-paxton** [dyscord-lab/SA_Stimulus#2]
Adding the world timestamp to the logfile would make it much easier to integrate with Pupil output.

**Comment by a-paxton** [comment]
https://discourse.psychopy.org/t/adding-precise-measure-of-system-clock-to-psychopy-output/8426

**Comment by mchiovaro** [comment]
System time added for onset/offset of stimuli and button pressing.
